version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ussd_postgres
    environment:
      POSTGRES_USER: livestock
      POSTGRES_PASSWORD: livestock
      POSTGRES_DB: livestock_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ussd_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
